# =============================================================================
# TERRAFORM BACKEND CONFIGURATION
# =============================================================================
# 
# This file configures Terraform to use remote state storage.
# The backend configuration references the storage account created by the
# bootstrap infrastructure.
#
# IMPORTANT: Update these values after running the bootstrap Terraform
# =============================================================================

terraform {
  backend "azurerm" {
    # Bootstrap infrastructure configuration
    # Generated by bootstrap deployment
    # Environment-specific state files are configured in workflows
    
    resource_group_name  = "ai-image-processor-bootstrap-rg"
    storage_account_name = "aiimgproctfea49iuul"
    container_name       = "tfstate"
    key                  = "terraform-dev.tfstate"  # Default for dev, overridden in workflows
    
    # State locking and consistency checking enabled
    # Storage account has versioning enabled for protection
  }
}
